### ISSUE TITLE
China can't pack

### ISSUE THREAD

**Issue by mygithub-hang** [asticode/go-astilectron-bundler#103]
I'm glad to see that you are still updating. Due to the domestic network environment in China, the download response package will time out when executing astilen-bundler bd. You can only manually download it and put it into the corresponding directory for compilation. Can you configure it in bundler.json? Mirror address, such as: https://registry.npmmirror.com/binary.html?path=electron/, so that China can compile normally, thank you very much.

看到您还在更新我很高兴，由于中国国内网络环境原因，执行astilectron-bundler bd会出现下载响应包超时的情况，只能人工下载放入对应目录进行编译，能否在bundler.json中配置镜像地址，比如：https://registry.npmmirror.com/binary.html?path=electron/，使中国可以正常编译，万分感谢。

**Comment by asticode** [comment]
Right now, the 2 downloaded objects are:

- https://github.com/asticode/astilectron/archive/v0.55.0.zip
- https://github.com/electron/electron/releases/download/v11.4.3/electron-v11.4.3-darwin-x64.zip

What would be the alternative URLs that would work in China?

**Comment by mygithub-hang** [comment]
The valid download address in China is：https://registry.npmmirror.com/-/binary/electron/v11.4.3/electron-v11.4.3-darwin-x64.zip
All files that need to be downloaded are currently mirrored in China：https://registry.npmmirror.com/binary.html?path=electron/
