### ISSUE TITLE
Relocate vendor and resources folders on windows?

### ISSUE THREAD

**Issue by fraserdale** [asticode/go-astilectron-bundler#14]
When running a compiled app on windows the following folder are created with the relevant contents. 
'vendor' and 'resources'
Is there a way that I can stop these being created in the same directory as the one that the app is executed in and stored elsewhere eg in the appdata folder

**Comment by asticode** [comment]
Duplicate of https://github.com/asticode/go-astilectron/issues/78, closing this issue
