### ISSUE TITLE
Create Linux packages for different distributions

### ISSUE THREAD

**Issue by veecue** [asticode/go-astilectron-bundler#2]
Arch linux for example has a .PKGBUILD logic, that easily allows users to create their own packages. However, the compilation usually happens on the user's PC, so this bundler would have to provide a .PKGBUILD and a file with the neccessary assets (icons, etc.). I don't know, how it works on other Distributions like debian

**Comment by asticode** [comment]
As I said in #1, as of now this seems overly complicated to me (however intellectually appealing) as I want to keep the bundler tight and simple.

I'll keep this issue opened nonetheless to see if other people need this feature.

**Comment by asticode** [comment]
Closing this issue for now but still waiting to see whether more people need this feature
