### ISSUE TITLE
Index.html not updating when rebuilding application.

### ISSUE THREAD

**Issue by jacobdekeizer** [asticode/go-astilectron-bundler#21]
Hello,

My electron application is not updating when I change the html page.
The bundler takes always the html page from the first build.
I run this command: astilectron-bundler -v with Windows 10.
Wich command do I need to run to rebuild the application with the new html page?

Thanks

**Comment by asticode** [comment]
@jacobdekeizer `astilectron-bundler -v` should do the trick when it comes to rebuilding the application after having updated the html page. Can you paste the commands and the logs you get when you bundle *AND* when you execute the application?

**Comment by jacobdekeizer** [comment]
`{"level":"debug","msg":"Resetting","time":"2018-04-16T14:25:30+02:00"}
{"level":"debug","msg":"Creating C:\\Users\\jacob\\AppData\\Local\\Temp\\astibundler","time":"2018-04-16T14:25:30+02:00"}
{"level":"debug","msg":"Creating C:\\Users\\jacob\\Documents\\Unity\\Intersection\\Controller\\output","time":"2018-04-16T14:25:30+02:00"}
{"level":"debug","msg":"Bundling for environment windows/amd64","time":"2018-04-16T14:25:30+02:00"}
{"level":"debug","msg":"Removing C:\\Users\\jacob\\Documents\\Unity\\Intersection\\Controller\\output\\windows-amd64","time":"2018-04-16T14:25:30+02:00"}
{"level":"debug","msg":"Creating C:\\Users\\jacob\\Documents\\Unity\\Intersection\\Controller\\output\\windows-amd64","time":"2018-04-16T14:25:30+02:00"}
{"level":"debug","msg":"Binding data","time":"2018-04-16T14:25:30+02:00"}
{"level":"debug","msg":"Removing C:\\Users\\jacob\\Documents\\Unity\\Intersection\\Controller\\vendor_astilectron_bundler","time":"2018-04-16T14:25:30+02:00"}
{"level":"debug","msg":"Creating C:\\Users\\jacob\\Documents\\Unity\\Intersection\\Controller\\vendor_astilectron_bundler","time":"2018-04-16T14:25:30+02:00"}
{"level":"debug","msg":"C:\\Users\\jacob\\AppData\\Local\\Temp\\astibundler\\astilectron-0.20.0.zip already exists, skipping download of https://github.com/asticode/astilectron/archive/v0.20.0.zip","time":"2018-04-16T14:25:30+02:00"}
{"level":"debug","msg":"Copying C:\\Users\\jacob\\AppData\\Local\\Temp\\astibundler\\astilectron-0.20.0.zip to C:\\Users\\jacob\\Documents\\Unity\\Intersection\\Controller\\vendor_astilectron_bundler\\astilectron.zip","time":"2018-04-16T14:25:30+02:00"}
{"level":"debug","msg":"C:\\Users\\jacob\\AppData\\Local\\Temp\\astibundler\\electron-windows-amd64-1.8.1.zip already exists, skipping download of https://github.com/electron/electron/releases/download/v1.8.1/electron-v1.8.1-win32-x64.zip","time":"2018-04-16T14:25:30+02:00"}
{"level":"debug","msg":"Copying C:\\Users\\jacob\\AppData\\Local\\Temp\\astibundler\\electron-windows-amd64-1.8.1.zip to C:\\Users\\jacob\\Documents\\Unity\\Intersection\\Controller\\vendor_astilectron_bundler\\electron.zip","time":"2018-04-16T14:25:30+02:00"}
{"level":"debug","msg":"Generating C:\\Users\\jacob\\Documents\\Unity\\Intersection\\Controller\\bind_windows_amd64.go","time":"2018-04-16T14:25:30+02:00"}
{"level":"debug","msg":"Running rsrc for icon C:\\Users\\jacob\\Documents\\Unity\\Intersection\\Controller\\resources\\icon.ico into C:\\Users\\jacob\\Documents\\Unity\\Intersection\\Controller\\windows.syso","time":"2018-04-16T14:25:36+02:00"}
{"level":"debug","msg":"Building for os windows and arch amd64","time":"2018-04-16T14:25:36+02:00"}
{"level":"debug","msg":"Executing go build -ldflags -s -X \"main.AppName=Intersection_Controller\" -X \"main.BuiltAt=2018-04-16 14:25:36.7599804 +0200 CEST m=+6.291164801\" -H windowsgui -o C:\\Users\\jacob\\Documents\\Unity\\Intersection\\Controller\\output\\windows-amd64\\binary ","time":"2018-04-16T14:25:36+02:00"}
{"level":"debug","msg":"Moving C:\\Users\\jacob\\Documents\\Unity\\Intersection\\Controller\\output\\windows-amd64\\binary to C:\\Users\\jacob\\Documents\\Unity\\Intersection\\Controller\\output\\windows-amd64\\Intersection_Controller.exe","time":"2018-04-16T14:25:56+02:00"}`


The application says "running app". 

The window pops up but doesn't display the new html page.

**Comment by jacobdekeizer** [comment]
@asticode If i rename the file and set that filename in my main.go, then I get an empty template in my electron application. 

My resources are in /resources/app.

**Comment by jacobdekeizer** [comment]
@asticode I think I found the problem. 
If if build the application the html files electron uses are located in C:\Users\jacob\AppData\Roaming\resources\app. But they don't get updated until I delete the resources folder in Appdata\Roaming.

**Comment by asticode** [comment]
Mmmmmm indeed, I didn't think of that, sorry. When developing, you need to clean the `resources` folder for it to be updated, otherwise when launching the app it will detect the folder and disable disembedding it.

Is your issue fixed ?

**Comment by jacobdekeizer** [comment]
Yes, but maybe there needs to be an automated solution for all the windows users.
Thanks.

**Comment by asticode** [comment]
Sure, sounds like a good idea. I'll keep you posted.

**Comment by asticode** [comment]
Moving this issue to [this one](https://github.com/asticode/go-astilectron-bootstrap/issues/9)

**Comment by asticode** [comment]
@jacobdekeizer the bootstrap has been updated to force disembedding resources when some files have been changed. 

All you need to do is add the `AssetDir` option like in [the demo](https://github.com/asticode/go-astilectron-demo/blob/master/main.go#L36).

Let me know how it goes.
