### ISSUE TITLE
Bundling fail for windows (target OS) in Mac

### ISSUE THREAD

**Issue by apnerve** [asticode/go-astilectron-bundler#22]
I'm using MacOS (High Sierra) to bundle the app for windows.  I get this error

`bundling failed: bundling for environment windows/amd64 failed: building failed: # runtime/cgo
exec: "x86_64-w64-mingw32-gcc": executable file not found in $PATH`

Should I be installing something to make this work?

**Comment by asticode** [comment]
@apnerve this is a golang error, not an astilectron specific one therefore I can point you in the right direction but there's nothing more I can do.

It seems you're using CGO and you're trying to cross compile. Therefore you need to set up the proper toolchains to make this work. I urge you to try to build your project manually for Windows without using the bundler to make sure your environment is properly set up.

Again, as it's a not an astilectron error there's nothing more I can do.

Cheers

**Comment by vidmed** [comment]
This PR is that you are looking for. https://github.com/asticode/go-astilectron-bundler/pull/18
But unfortunately I have no time at the moment to work on it. If you have some time - you are welcome to finish it.

**Comment by asticode** [comment]
@apnerve did you manage to fix your problem?

**Comment by apnerve** [comment]
@asticode Not yet. I decided to take a pure electron approach for now.

**Comment by apnerve** [comment]
Also, looks like I need to build for windows on a windows machine. It doesn't have anything to do with astilectron and hence closing this issue.

**Comment by asticode** [comment]
Thanks for the update.

Cheers.
