### ISSUE TITLE
codesign verification rejected "the code is valid but does not seem to be an app" 

### ISSUE THREAD

**Issue by hunterlong** [asticode/go-astilectron-bundler#23]
Great app, love to use Go with Electron. I have an issue signing the .app with codesign though, more of an issue verifying with `spctl`. I have a valid certificate and I've done code signing before, I've only ran into an issue with this golang/electron app. 

Using the `go-astilectron-demo` project, these are the commands I run.

- **Build .app** `astilectron-bundler -v`

- **Sign .app** `codesign --deep --strict --force --verbose=4 --sign <my cert here> "Astilectron demo.app"`

- **Verify .app** `spctl -vvvv -a "Astilectron demo.app"`
This is where the issue happens. The response from spctl is: 
```
Astilectron demo.app: rejected (the code is valid but does not seem to be an app)
origin=<my cert here>
```

Anyone else having this issue? I've tried multiple methods with no luck.

**Comment by asticode** [comment]
@hunterlong this must be because the bundler creates the MaxOSX app manually. Something must be missing unfortunately. Is there any way you could share a minimalist app that you actually succeed to sign? Since a MacOSX app is a folder containing few files in a specific folder tree, I'm interested in checking whether I've not omitted anything that would make the signing fail.

Let me know.

**Comment by hunterlong** [comment]
Thanks for getting back to me so quickly. I've been able to sign electron apps for Mac and Windows using p12 certificates. [electron-builder](https://www.electron.build/code-signing) makes the code signing process mostly automatic. electron-builder does seem to be using `codesign` though.

The project i've been working with is [CoinApp](https://github.com/coinapp-io/desktop), it's open source and is just a basic electron app. (not as complexed as this project) Building and signing is done on travis-ci so you can see how it's done. I'm thinking there's an issue with the generated Info.plist file? Maybe?

**Comment by asticode** [comment]
That's my guess too. Or another needed file may be missing in the App created by the bundler.

In any case, is there any way you could zip the `CoinApp` built with `electron-builder` and share it on this issue? I don't have the full electron toolchain installed, and I'd rather check evertyhing on a valid app.
