### ISSUE TITLE
Cooperate with other build tools, for example: https://github.com/lunny/gop

### ISSUE THREAD

**Issue by lunny** [asticode/go-astilectron-bundler#3]
I used https://github.com/lunny/gop to manage my repos which is not in $GOPATH. Could the bunlder be more flexible to cooperate with this build tool? moved from asticode/go-astilectron#38

**Comment by asticode** [comment]
@lunny I'd be glad to try it :)

Can you try bundling the [demo](https://github.com/asticode/go-astilectron-demo) with the `-v` and tell me at which step it fails by pasting the logs here?

**Comment by lunny** [comment]
@asticode I have tried the demo. It works well on my macOS.

**Comment by asticode** [comment]
@lunny do you know what is missing from the bundler to work with https://github.com/lunny/gop then?

**Comment by lunny** [comment]
Since `gop` is a compitable tool with `go`, I think maybe you should let `go` command configrable.

**Comment by asticode** [comment]
does `gop build` allows flags such as `-o` or `ldflags` ?

**Comment by lunny** [comment]
@asticoe. Yes.

**Comment by asticode** [comment]
@lunny I've added the go binary path to the configuration. It's available in the `go_binary_path` key. Is the bundler now working with gop?

**Comment by asticode** [comment]
@lunny can we consider this issue as fixed?

**Comment by lunny** [comment]
@asticode sorry, I maybe test this tomorrow.

**Comment by asticode** [comment]
@lunny no problem, let me know how your tests go

**Comment by lunny** [comment]
@asticode I have sent #6 and #7, I think maybe I can test my project after that PRs merged.
