### ISSUE TITLE
Mac OS X open file limit

### ISSUE THREAD

**Issue by deepch** [asticode/go-astilectron-bundler#4]
I use many sockets to scan the network.

Problem Max Open File limit

i no have problem

```
go run *.go
```

if use bundler generate app 

```
Too many open files in system
```

perhaps somewhere in the package you need to specify the maximum number of file descriptors.

perhaps than it will help.

https://superuser.com/questions/433746/is-there-a-fix-for-the-too-many-open-files-in-system-error-on-os-x-10-7-1

**Comment by deepch** [comment]
I think I have to do dmg and add a file
---> sudo launchctl load /Library/LaunchDaemons/name

https://serverfault.com/questions/15564/where-are-the-default-ulimits-specified-on-os-x-10-5

**Comment by asticode** [comment]
mmm this is weird that you don't get the error while running `go run *.go`. I'm far from being a MacOSX expert but my guess is that when using the bundler, we set up a real MacOSX app and therefore MacOSX may give it additionnal limits.

Can you tell me the exact number of opened files:
- when running `go run *.go`
- when running the bundler generated app

**Comment by deepch** [comment]
I have 100 wokers and regular POST requests, I close the connection after using.

You are right, it seems that the collected package has fewer restrictions. I will read how to increase the limit to avoid this. But while it really is.

**Comment by deepch** [comment]
i found solution 

if only bundler 

![2017-09-09 16 45 03](https://user-images.githubusercontent.com/7899955/30240722-7bf92464-957e-11e7-8603-bb6e31447c2a.png)


if add code in main.go

```
        var rLimit syscall.Rlimit
	rLimit.Max = 999999
	rLimit.Cur = 999999
	err = syscall.Setrlimit(syscall.RLIMIT_NOFILE, &rLimit)
	if err != nil {
		fmt.Println("Error Setting Rlimit ", err)
	}
```

![2017-09-09 16 45 41](https://user-images.githubusercontent.com/7899955/30240727-898517d2-957e-11e7-8fd9-2bceabac989b.png)

my problem is solved, it would be nice to add this to the main code if possible.

```


	var rLimit syscall.Rlimit
	err := syscall.Getrlimit(syscall.RLIMIT_NOFILE, &rLimit)
	if err != nil {
		fmt.Println("Error Getting Rlimit ", err)
	}
	fmt.Println(rLimit)
	rLimit.Max = 999999
	rLimit.Cur = 999999
	err = syscall.Setrlimit(syscall.RLIMIT_NOFILE, &rLimit)
	if err != nil {
		fmt.Println("Error Setting Rlimit ", err)
	}
	err = syscall.Getrlimit(syscall.RLIMIT_NOFILE, &rLimit)
	if err != nil {
		fmt.Println("Error Getting Rlimit ", err)
	}
	fmt.Println("Rlimit Final", rLimit)
```

You can learn the limits and change them quite simply, but without this there are strict restrictions.

**Comment by asticode** [comment]
@deepch I'm glad you fixed this problem, closing this issue
