### ISSUE TITLE
Include electron in app on Mac OS

### ISSUE THREAD

**Issue by Chinyaev** [asticode/go-astilectron-bundler#42]
Hi!

When I make "astilectron-bundler" on Mac OS - I get app without electron in package. It starts downloading in package/macos/vendor...and it long and app crash. If manually copy folder vendor to package app work fine but app size > 200mb. How include electron in package? And how make size less? Sorry for my English

**Comment by asticode** [comment]
@Chinyaev when you use the bundler, the compressed Electron binaries are binded to the Golang binary and when you open the Golang binary, the binded resources should be extracted on your local disk. Therefore everything should be working OK.

Could you paste some code or some log that could help me figure out your problem?

**Comment by Chinyaev** [comment]
my main.go:
`var a, _ = astilectron.New(astilectron.Options{
		AppName: "Astilectron",
	})
	defer a.Close()
	a.Start()
	var w, _ = a.NewWindow("http://google.com", &astilectron.WindowOptions{
		Center: astilectron.PtrBool(true),
		Height: astilectron.PtrInt(600),
		Width:  astilectron.PtrInt(1000),
	})
	w.Create()
a.Wait()
`

bandler.json:
`{
    "app_name": "Astilectron",
    "icon_path_darwin": "resources/icon.icns",
    "icon_path_linux": "resources/icon.png",
    "icon_path_windows": "resources/icon.ico"
}`

build command: astilectron-bundler -v

package after build don't have electron:
<img width="622" alt="2019-02-18 17 48 56" src="https://user-images.githubusercontent.com/25378292/52958864-056b0c00-33a6-11e9-9072-843cfe3177cd.png">
before build I run (go run main.go) the app and electron downloaded to the vendor folder

**Comment by asticode** [comment]
As I mentionned in my previous comment, Electron is binded to the Golang binary and is extracted on disk when first running the binary. Therefore the Electron binary is available once the Golang app has been started.

Does it answer your question?
