### ISSUE TITLE
How do I package an executable file into an osx app

### ISSUE THREAD

**Issue by weiki-li** [asticode/go-astilectron-bundler#46]
How do I package an executable file into an osx app

**Comment by asticode** [comment]
Are you looking to package an `astilectron` project, or any kind of executable?

**Comment by weiki-li** [comment]
I want to package any kind of executable to output app

**Comment by asticode** [comment]
[This article](http://www.zitnik.si/wordpress/2016/02/21/creating-a-mac-os-app-from-a-runnable-jar-file/) would be a good start. Bare in mind that I've just done a simple Google search with the terms "how to create macosx app from executable".
Otherwise you can dig in the code of this project.

**Comment by weiki-li** [comment]
What does "go_binary_path" do？Can I configure the executable to go to "go_binary_path"

**Comment by asticode** [comment]
Read the article first, it's pretty straight forward

**Comment by weiki-li** [comment]
I read the article,but I mean I wrote the page(js/html/css) myself, and the executable is a go service that provides the page data,so I want to use go-astilectron-bundler to package my page and go service into app/exe

**Comment by asticode** [comment]
Then I'd suggest you check [the demo](https://github.com/asticode/go-astilectron-demo) out to see how you can use `go-astilectron` and its `bundler` to bundle your app.
