### ISSUE TITLE
astilectron-bundler does not emit logs when output is redirected

### ISSUE THREAD

**Issue by dhawth** [asticode/go-astilectron-bundler#53]
to reproduce, try:

astilectron-bundler -v | tee bundler.log
astilectron-bundler -v >bundler.log

I'm trying to capture the output of astilectron-bundler to compare what it is doing while reproducing a bug in go-astilectron-demo, and this inability to capture that log is frustrating.

**Comment by asticode** [comment]
@dhawth I've pushed a fix in `github.com/asticode/go-astilog` that should fix this issue. I don't know which vendor workflow you're using but in any case you can try pulling `master` of this dependency and you should see your logs even when redirecting `stdout`.

I'll close this issue for now but feel free to reopen it if you're facing some issues.
