### ISSUE TITLE
fatal: Not possible to fast-forward, aborting.

### ISSUE THREAD

**Issue by uchobby** [asticode/go-astilectron-bundler#54]
Just tried to follow the install instructions and get an error:
>go get -u github.com/asticode/go-astilectron-bundler/...
# cd ~~\go\src\github.com\asticode\go-astilectron-bundler; git pull --ff-only
fatal: Not possible to fast-forward, aborting.
package github.com/asticode/go-astilectron-bundler: exit status 128

**Comment by asticode** [comment]
Can you execute the `go get` command with the `-v` flag ?

`go get -u -v github.com/asticode/go-astilectron-bundler/...`

**Comment by uchobby** [comment]
C:\Users\David Fowler\go\bin>go get -u -v github.com/asticode/go-astilectron-bundler/...
github.com/asticode/go-astilectron-bundler (download)
# cd C:\Users\David Fowler\go\src\github.com\asticode\go-astilectron-bundler; git pull --ff-only
fatal: Not possible to fast-forward, aborting.
package github.com/asticode/go-astilectron-bundler: exit status 128
github.com/asticode/go-astilog (download)
github.com/mattn/go-colorable (download)
github.com/mattn/go-isatty (download)
github.com/pkg/errors (download)
github.com/sirupsen/logrus (download)
github.com/konsorten/go-windows-terminal-sequences (download)
Fetching https://golang.org/x/crypto/ssh/terminal?go-get=1
Parsing meta tags from https://golang.org/x/crypto/ssh/terminal?go-get=1 (status code 200)
get "golang.org/x/crypto/ssh/terminal": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/ssh/terminal?go-get=1
get "golang.org/x/crypto/ssh/terminal": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
golang.org/x/crypto (download)
Fetching https://golang.org/x/sys/windows?go-get=1
Parsing meta tags from https://golang.org/x/sys/windows?go-get=1 (status code 200)
get "golang.org/x/sys/windows": found meta tag get.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at https://golang.org/x/sys/windows?go-get=1
get "golang.org/x/sys/windows": verifying non-authoritative meta tag
Fetching https://golang.org/x/sys?go-get=1
Parsing meta tags from https://golang.org/x/sys?go-get=1 (status code 200)
golang.org/x/sys (download)
github.com/asticode/go-astitools (download)

**Comment by asticode** [comment]
Mmm maybe you have unstaged changes in the repo. Can you `rm -rf github.com/asticode/go-astilectron-bundler` and try again `go get -u -v github.com/asticode/go-astilectron-bundler/...` ?
