### ISSUE TITLE
A 300MB+ go file is generated.

### ISSUE THREAD

**Issue by zhb1207** [asticode/go-astilectron-bundler#55]
Hi, thanks for your great work!
I used this tool to bundle the demo, and a file "bind_linux_amd64.go" is generated, I noticed the file has only 748 lines but has a size of 302.4MB. Could you please help with this problem?
Thanks.

**Comment by asticode** [comment]
This is normal. This file contains the binded resources needed to run astilectron afterwards. You'll see that some of the lines are very long []byte; those lines are the ones taking up all this space.
