### ISSUE TITLE
Document not clear

### ISSUE THREAD

**Issue by soumyart** [asticode/go-astilectron-bundler#56]
Need clarification on following points:

1. Is it mandatory to use [go-astilectron-bootstrap](https://github.com/asticode/go-astilectron-bootstrap) for bundler to work?
2. If I create a basic app using the guides from [go-astielectron](https://github.com/asticode/go-astilectron), how to use the bundler. I tried but the bundled exe is not opening. No errors to trace.

**Comment by asticode** [comment]
1. It's not mandatory but it's highly recommended as I haven't tested thoroughly using the bundler without the bootstrap.
2. What command are you using to execute the bundler? And where compared to you astilectron app?
