### ISSUE TITLE
How to show console

### ISSUE THREAD

**Issue by Philiphil** [asticode/go-astilectron-bundler#59]
Hi,
I'd like to show console for debuging purpose, but can't find how to, can you help me ?

**Comment by asticode** [comment]
Sure, you have 2 ways:

- if you're using the [bootstrap](https://github.com/asticode/go-astilectron-bootstrap), you need to set the [Debug](https://github.com/asticode/go-astilectron-bootstrap/blob/master/options.go#L13) option to `true`. Then, in the menu, you should see a "Debug" item : click it to open the dev tools.
- if you're doing things manually, you simply need to call either `OpenDevTools()` or `CloseDevTools` of the window you've created.

Does that answer your question?

**Comment by Philiphil** [comment]
Thank's, but i'm not asking for devtools, but for a CLI

**Comment by asticode** [comment]
Which OS are you using ?

**Comment by Philiphil** [comment]
windows 10

**Comment by asticode** [comment]
Are you using the bundler ?

**Comment by Philiphil** [comment]
yes

**Comment by asticode** [comment]
I've added a `show_windows_console` option to the bundler. Set it to `true` in your `bundler.json` and should show the console when you run the `.exe` file.

Does that fix your problem ?

**Comment by Philiphil** [comment]
Yes, worked like a charm, thank's a lot
