### ISSUE TITLE
Could manually download electron-v4.0.1-darwin-x64.zip? 

### ISSUE THREAD

**Issue by ajeecai** [asticode/go-astilectron-bundler#62]
Due to the some network problem, I could not download the necessary components:

> DEBU[0029] Downloading https://github.com/electron/electron/releases/download/v4.0.1/electron-v4.0.1-darwin-x64.zip into /tmp/astibundler/cache/electron-darwin-amd64-4.0.1.zip  source="helper.go:22"
> 
> DEBU[0430] Removing /tmp/astibundler/cache/electron-darwin-amd64-4.0.1.zip...  source="helper.go:36"
> FATA[0430] bundling failed: bundling for environment darwin/amd64 failed: binding data failed: provisioning the vendor failed: provisioning electron vendor for OS darwin and arch amd64 failed: downloading https://github.com/electron/electron/releases/download/v4.0.1/electron-v4.0.1-darwin-x64.zip into /tmp/astibundler/cache/electron-darwin-amd64-4.0.1.zip failed: astihttp.Download failed: astihttp: downloading in writer failed: astihttp: copying content from https://github.com/electron/electron/releases/download/v4.0.1/electron-v4.0.1-darwin-x64.zip to writer failed: read tcp 10.10.10.10:39316->52.216.170.163:443: read: connection reset by peer  source="main.go:122"

manually try to download electron-v4.0.1-darwin-x64.zip and put it into /tmp/astibundler/cache/, still doesn't work.

Thanks

**Comment by asticode** [comment]
Logs say `downloading https://github.com/electron/electron/releases/download/v4.0.1/electron-v4.0.1-darwin-x64.zip into /tmp/astibundler/cache/electron-darwin-amd64-4.0.1.zip failed` therefore you need to download `https://github.com/electron/electron/releases/download/v4.0.1/electron-v4.0.1-darwin-x64.zip`, put it in `/tmp/astibundler/cache` **and rename the file to electron-darwin-amd64-4.0.1.zip**.

The last part it the most important bit I think!

Does it fix your problem ?

**Comment by ajeecai** [comment]
ok, the network back to normal and I don't try this workaround  any more. Thanks, let me close it.
