### ISSUE TITLE
Not allowed to load local resource (Linux AMD64)

### ISSUE THREAD

**Issue by Happy-Ferret** [asticode/go-astilectron-bundler#63]
Hi.

I have the problem that, under GNU/Linux (Microsoft WSL), the desktop build of my app fails to load with the following error logged to debug.

``Not allowed to load local resource: file:///mnt/c/Users/user/Desktop/git/yggdrasil/resources/app/index.html%3Flang=C``

The same app works fine under Windows.

**Comment by asticode** [comment]
Can you share the args you're passing to the `NewWindow` method ?

**Comment by Happy-Ferret** [comment]
I'm using go-astilectron-bootstrap, so it looks as follows:

```go
Windows: []*bootstrap.Window{{
			Homepage:       "index.html?lang=" + lang,
			MessageHandler: handleMessages,
			Options: &astilectron.WindowOptions{
				BackgroundColor: astikit.StrPtr("#5cc070"),
				Center:          astikit.BoolPtr(true),
				Height:          astikit.IntPtr(700),
				Width:           astikit.IntPtr(700),
			},
		}},
```

Where ``lang`` is a string like "en" or "fr", typically.

**Comment by asticode** [comment]
Does the path `/mnt/c/Users/user/Desktop/git/yggdrasil/resources/app/index.html` exist on your machine ?

**Comment by Happy-Ferret** [comment]
I'm currently away, but that's interesting. I believe it's missing the "desktop-app" in-between "yggdrasil" and "resources".

**Comment by asticode** [comment]
Since you've posted the issue in the `bundler` repo, I assume that you're using it. Can you :

- fetch the last `bundler` + `astilectron` changes
- make sure to build the `bundler`
- paste logs when you `bundle` as well as when you `run` the app

I'd like to see how paths are handled in the process.
