### ISSUE TITLE
launch daemon fail when package the app

### ISSUE THREAD

**Issue by akzhou** [asticode/go-astilectron-bundler#68]
@asticode  why I  could launch a daemon  by  bash shell from app (go run main.go) or terminal,
but not work  when package from "astilectron-bundler".

**Comment by asticode** [comment]
Maybe the path you provide for your bash shell is valid when running from app, but invalid after packaging. Can you share some code so that I can take a look?

**Comment by akzhou** [comment]
> Maybe the path you provide for your bash shell is valid when running from app, but invalid after packaging. Can you share some code so that I can take a look?

I run go build -o CCat and double click the app,
```
open daemon failed:,{
    NSAppleScriptErrorAppName = CCat;
    NSAppleScriptErrorBriefMessage = "Authorization failed.";
    NSAppleScriptErrorMessage = "Authorization failed.";
    NSAppleScriptErrorRange = "NSRange: {1, 113}";
}
cmd: do shell script "/Users/ak/Library/Application' 'Support/CCat/CCatHelper "  with administrator privileges 
```

**Comment by akzhou** [comment]
oh, It's the daemon pid path error,thanks!! :)

**Comment by asticode** [comment]
Cheers
