### ISSUE TITLE
Question. How can I zip output of the bundler?

### ISSUE THREAD

**Issue by tpoxa** [asticode/go-astilectron-bundler#76]
I am experiencing problems with .app extension in my CI, because its actually folder. I would like to zip .app application as soon as its built. Can I do it with the bundler? Do I need to use resources adapters? 

Thanks in advance.

**Comment by asticode** [comment]
Why don't you zip the .app file as soon as the bundler is done in your CI workflow ?

**Comment by tpoxa** [comment]
Yes, I did. Just thought using bundler may be a good idea. Nevermind :) 
Thank you for great project!

**Comment by tpoxa** [comment]
Hello @asticode It's me again. Can you help me with saying how to make different names for appName and actual output file name?
Thank you!

**Comment by asticode** [comment]
@tpoxa you can set a different AppName by using [this attribute](https://github.com/asticode/go-astilectron-bundler/blob/master/bundler.go#L27). This is global to a `bundler.json` file though.

You can't set the output file names. However they are predictible, so after the bundler is done, you can rename them however you like.

**Comment by tpoxa** [comment]
I see. Thanks for an update. In my project application name comes from user’s input. I thought it should be different levels of sanitizing input for filename and app name.
