### ISSUE TITLE
'astilectron-bundler' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by ericdgit** [asticode/go-astilectron-bundler#8]
Hi! When I run the command `astilectron-bundler -v` I get the following error-response:

``'astilectron-bundler' is not recognized as an internal or external command, operable program or batch file.``

I'm on windows 10.

**Comment by asticode** [comment]
@ericdgit is `$GOPATH/bin` in your `$PATH` ?

**Comment by ericdgit** [comment]
Ah, that's where the exe-file is! :) I was missing the environment variable. Thanks for pointing out the obvious. Perhaps it would be nice to add a note about this to the installation instruction. If more ignorant users like myself comes along :)

**Comment by asticode** [comment]
@ericdgit I've updated the readme of the demo to add this information :)
