### ISSUE TITLE
using go-astilectron-bundler without go-astilectron-bootstrap possible?

### ISSUE THREAD

**Issue by bogdanfinn** [asticode/go-astilectron-bundler#82]
Sorry for that maybe dumb question, but is it actually possible to use the go-astilectron-bundler without go-astilectron-bootstrap? Only using go-astilectron?

**Comment by asticode** [comment]
You don't have to use the `bootstrap` however it's strongly recommended. Indeed if you only use `go-astilectron` you'll have to re-implement [this part](https://github.com/asticode/go-astilectron-bootstrap/blob/master/run.go#L18)

**Comment by bogdanfinn** [comment]
@asticode Thank you very much for the quick answer.
