### ISSUE TITLE
Disables the terminal display

### ISSUE THREAD

**Issue by true-zero** [asticode/go-astilectron-bundler#91]
Possibly intentional behaviour by the bundler. But for command-line applications this behaviour is undesired. Is it possible to have the command line interface still be visible.

**Comment by asticode** [comment]
I guess you're mentionning the issue for Windows only. In that case you could use the [show_windows_console](https://github.com/asticode/go-astilectron-bundler/blob/master/bundler.go#L82) option in your `bundler.json`.

Let me know if that fixes your problem.

**Comment by true-zero** [comment]
That fixed the issue, thank you.
