### ISSUE TITLE
Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

### ISSUE THREAD

**Issue by vivekvardha** [asticode/go-astilectron-bundler#94]
I am facing the error  in title when I try to run the app with sudo privileges.

I created the new window as follows.

```
	var w *astilectron.Window
	if w, err = a.NewWindow("sample/logs.html", &astilectron.WindowOptions{
		Center:   astikit.BoolPtr(true),
		Height:   astikit.IntPtr(700),
		Width:    astikit.IntPtr(700),
		MinWidth: astikit.IntPtr(100),
		**WebPreferences: &astilectron.WebPreferences{Sandbox: astikit.BoolPtr(false)}**,
	}); err != nil {
		log.Println(fmt.Sprintf("main: new window failed: %w", err))
	}
```

By initializing Sandbox under WebPreferences to 'false', I thought it would solve the problem but it did not work.
Any leads to fix/workaround this would be of great help.

**Comment by asticode** [comment]
You could try using [ElectronSwitches](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L71). Basically they are flags you can provide to Electron. 

In your case you could try setting it to `[]string{"--no-sandbox"}`

**Comment by vivekvardha** [comment]
@asticode thanks a lot for the quick input. 
It worked :)

**Comment by asticode** [comment]
Cheers
