### ISSUE TITLE
astikit: invalid status code 404

### ISSUE THREAD

**Issue by Adolph-InnerMongolia** [asticode/go-astilectron-bundler#97]
/Contents/MacOS/vendor/astilectron-v1.0.zip failed: DownloadInFile failed: astikit: response for request to https://github.com/asticode/astilectron/archive/v1.0.zip is invalid: astikit: invalid status code 404

**Comment by asticode** [comment]
The `astilectron` version is invalid (`v1.0.`). Did you set it manually ?

**Comment by Adolph-InnerMongolia** [comment]
Not set

**Comment by Adolph-InnerMongolia** [comment]
> The `astilectron` version is invalid (`v1.0.`). Did you set it manually ?

Not set

**Comment by Adolph-InnerMongolia** [comment]
I am using a mac M1
