### ISSUE TITLE
How to not request download "electron" ?

### ISSUE THREAD

**Issue by mzky** [asticode/go-astilectron-bundler#99]
Please excuse my poor English. I have a very small demo. After bundler, the file is in 80M, so it can be seen that the "electron" file is included, but I am still requesting to download the "electron" file when I run it. May I ask if there is anything else I need to configure?  

![image](https://user-images.githubusercontent.com/13345233/150720489-5549ad4d-7e10-4092-8264-08419f552c68.png)

bundler.js
```
{
  "app_name": "demo",
  "icon_path_darwin": "resources/icon.icns",
  "icon_path_linux": "resources/icon.png",
  "icon_path_windows": "resources/icon.ico",
  "environments": [
    {
      "arch": "amd64",
      "os": "linux"
    }
  ]
}
```

demo.go
```
package main

import (
	"log"
	"os"

	"github.com/asticode/go-astikit"
	"github.com/asticode/go-astilectron"
)

func main() {
	a, _ := astilectron.New(log.New(os.Stderr, "", 0), astilectron.Options{
		AppName:            "desktop",
		AppIconDefaultPath: "./icon.png",
	})
	defer a.Close()

	a.Start()

	var w, _ = a.NewWindow("https://www.google.com", &astilectron.WindowOptions{
		Center: astikit.BoolPtr(true),
	})
	w.Create()
	
	a.Wait()
}
```

**Comment by asticode** [comment]
Adding only the `bundler.json` file is not sufficient to use the `bundler`.

If you checkout the [demo](https://github.com/asticode/go-astilectron-demo/blob/master/main.go#L44), you can see that everything is wrapped in the `bootstrap.Run` function which is mandatory if you want to use the `bundler`.

**Comment by mzky** [comment]
thank you for response .
Yes, I saw the `bootstrap.Run(bootstrap.Options{` thing, but I want to go directly to the URL.
How does `bootstrap.Run` access URL.

**Comment by asticode** [comment]
First off, in the code you share, the following part is useless :
```
// Initialize astilectron
	a, _ := astilectron.New(log.New(os.Stderr, "", 0), astilectron.Options{
		AppName:            "demo",
		AppIconDefaultPath: "./icon.png",
	})
	defer a.Close()

	a.Start()

	var w, _ = a.NewWindow("https://www.google.com", &astilectron.WindowOptions{
		BackgroundColor: astikit.StrPtr("#333"),
		Center:          astikit.BoolPtr(true),
		Height:          astikit.IntPtr(700),
		Width:           astikit.IntPtr(700),
	})
	w.Create()

	a.Wait()
```

`bootstrap.Run` will take care of doing that part

**Comment by asticode** [comment]
You can provide your URL directly in the `bootstrap.Options`. Checkout [here](https://github.com/asticode/go-astilectron-demo/blob/master/main.go#L91).

**Comment by mzky** [comment]
It is running normally. Thank you again.
